/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mvictor.app.view;


import br.com.mvictor.app.support.Validacao;
import br.com.mvictor.cliente.dao.PessoaDao;
import br.com.mvictor.cliente.model.Pessoa;
import br.com.mvictor.cliente.model.Contato;
import br.com.mvictor.cliente.model.Endereco;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author mvictor
 */
public class Cadastro extends javax.swing.JFrame {

    
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        //this.setExtendedState(Cadastro.MAXIMIZED_BOTH);
        this.txtBairro.setBorder(new LineBorder(Color.BLACK));
        this.txtCelS.setBorder(new LineBorder(Color.BLACK));
        this.txtCep.setBorder(new LineBorder(Color.BLACK));
        this.txtCidade.setBorder(new LineBorder(Color.BLACK));
        this.txtComplemento.setBorder(new LineBorder(Color.BLACK));
        this.txtCpf.setBorder(new LineBorder(Color.BLACK));
        this.txtDtNasc.setBorder(new LineBorder(Color.BLACK));
        this.txtEmail.setBorder(new LineBorder(Color.BLACK));
        this.txtNome.setBorder(new LineBorder(Color.BLACK));
        this.txtRg.setBorder(new LineBorder(Color.BLACK));
        this.txtRua.setBorder(new LineBorder(Color.BLACK));
        this.txtCelP.setBorder(new LineBorder(Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        comboxSexo = new javax.swing.JComboBox<>();
        lblDtNasc = new javax.swing.JLabel();
        txtDtNasc = new javax.swing.JFormattedTextField();
        lblRg = new javax.swing.JLabel();
        txtRg = new javax.swing.JFormattedTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        comboxEstadoCivil = new javax.swing.JComboBox<>();
        lblCel = new javax.swing.JLabel();
        txtCelP = new javax.swing.JFormattedTextField();
        lblTel = new javax.swing.JLabel();
        txtCelS = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        panelEndereco = new javax.swing.JPanel();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        comboxEstado = new javax.swing.JComboBox<>();
        lblCep = new javax.swing.JLabel();
        spinerNumero = new javax.swing.JSpinner();
        txtCep = new javax.swing.JFormattedTextField();
        lblNumero = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        menuItemHome = new javax.swing.JMenuItem();
        menuItemBack = new javax.swing.JMenuItem();
        menuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA DE CADASTRO");

        panelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N

        lblNome.setText("Nome Completo");

        lblSexo.setText("Sexo");

        comboxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        lblDtNasc.setText("Data Nasc.");

        try {
            txtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblRg.setText("RG");

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCpf.setText("CPF");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEstadoCivil.setText("Estado Civíl");

        comboxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo", "Morando Junto" }));

        lblCel.setText("Cel");

        try {
            txtCelP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblTel.setText("Cel 2");

        try {
            txtCelS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEmail.setText("Email");

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(lblCel)
                    .addComponent(lblRg)
                    .addComponent(lblNome)
                    .addComponent(lblSexo))
                .addGap(28, 28, 28)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDtNasc)
                            .addComponent(lblEstadoCivil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegistroLayout.createSequentialGroup()
                                .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNome)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(txtCelP, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(lblTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCelS, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDtNasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoCivil)
                    .addComponent(comboxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mvictor/app/imagens/addCliente_icone.png"))); // NOI18N
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setFocusCycleRoot(true);
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        panelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblRua.setText("Rua");

        lblBairro.setText("Bairro");

        lblComplemento.setText("Compl.");

        lblCidade.setText("Cidade");

        lblEstado.setText("Estado");

        comboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amapá", "Acré", "Amazonas", "Bahia", "Distrito Federal", "São Paulo", "Rio de Janeiro", "Mato Grosso", "Mato Grosso do SUl", "Minas Gerais", "Santa Catarina", "Paraíba", "Paraná", "Pará", "Pernanbuco", "Ceará", "Maranhão", "Sergipe", "Rondônia", "Roraima", "Espirito Santo", "Rio Grande do Norte", "Rio Grande do Sul" }));

        lblCep.setText("CEP");

        spinerNumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblNumero.setText("Número");

        javax.swing.GroupLayout panelEnderecoLayout = new javax.swing.GroupLayout(panelEndereco);
        panelEndereco.setLayout(panelEnderecoLayout);
        panelEnderecoLayout.setHorizontalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCep)
                    .addComponent(lblCidade)
                    .addComponent(lblRua)
                    .addComponent(lblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelEnderecoLayout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEstado))
                            .addGroup(panelEnderecoLayout.createSequentialGroup()
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(lblNumero)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelEnderecoLayout.createSequentialGroup()
                                .addComponent(spinerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(txtRua))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        panelEnderecoLayout.setVerticalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mvictor/app/imagens/borracha_icone.png"))); // NOI18N
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setFocusCycleRoot(true);
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimparMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimparMouseEntered(evt);
            }
        });
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mvictor/app/imagens/home_icone.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusCycleRoot(true);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        menuOpcoes.setText("Opçoes");

        menuItemHome.setText("Tela Inicial");
        menuOpcoes.add(menuItemHome);

        menuItemBack.setText("Voltar");
        menuOpcoes.add(menuItemBack);

        menuItemSobre.setText("Sobre");
        menuOpcoes.add(menuItemSobre);

        jMenuBar1.add(menuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if(validaCampos())
        {
            PessoaDao dao = new PessoaDao();
            
            Pessoa cl = new Pessoa();
            
            cl.setNome(txtNome.getText());
            cl.setCpf(txtCpf.getText());
            cl.setRg(txtRg.getText());
            cl.setDtNasc(txtDtNasc.getText());
            cl.setSexo(comboxSexo.getSelectedItem().toString());
            cl.setEstadoCiv(comboxEstadoCivil.getSelectedItem().toString());
            
            Endereco end = new Endereco();
            end.setRua(txtRua.getText());
            end.setBairro(txtBairro.getText());
            end.setComplemento(txtComplemento.getText());
            end.setCep(txtCep.getText());
            end.setNumero((int)spinerNumero.getValue());
            end.setCidade(txtCidade.getText());
            end.setEstado(comboxEstado.getSelectedItem().toString());
   
            Contato cont = new Contato();
            cont.setCelP(txtCelP.getText());
            cont.setCelS(txtCelS.getText());
            cont.setEmail(txtEmail.getText());
            cont.setPessoa(cl);
            
            List <Contato> listaTel = new ArrayList();
            listaTel.add(cont);
            
            cl.setContatos(listaTel);
            cl.setEndereco(end);
            

            
            //cl.setContatos(listaTel);
            //cl.setEndereco(end);
            
            try{
                dao.inserir(cl);
                JOptionPane.showMessageDialog(this, "O cadastro foi realizado com sucesso...", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Erro, Não foi possível cadastrar!", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    public boolean validaCampos()
    {
        
        String nome = null;
        
        Validacao val = Validacao.getInstance();
        
        if(val.isEmpty(this.txtNome.getText()) || val.isNull(this.txtNome.getText()))
        {
            JOptionPane.showMessageDialog(this, "Campo nome vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtNome.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            nome = this.txtNome.getText();
            this.txtNome.setText(nome.toUpperCase());
            this.txtNome.setBorder(new LineBorder(Color.BLACK));
        }
        if(val.isEmpty(this.txtDtNasc, "  /  /    ") || val.isNull(this.txtDtNasc, null))
        {
            JOptionPane.showMessageDialog(this, "Campo Data de nascimento vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtDtNasc.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtDtNasc.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtCpf, "   .   .   -  ") || val.isNull(this.txtCpf, null))
        {
            JOptionPane.showMessageDialog(this, "Campo CPF vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtCpf.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtCpf.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtRg, "  .   .   - ") || val.isNull(this.txtRg, null))
        {
            JOptionPane.showMessageDialog(this, "Campo RG vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtRg.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtRg.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtCelP, "(  )-     -    ") || val.isNull(this.txtCelP, null))
        {
            JOptionPane.showMessageDialog(this, "Campo número de celular vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtCelP.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtCelP.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(txtCelS,"(  )-     -    ") || val.isNull(txtCelS, "(  )-     -    "))
        {
            this.txtCelS.setText(null);
        }
        
        if(val.isEmpty(this.txtEmail.getText()) || val.isNull(this.txtEmail.getText()))
        {
            JOptionPane.showMessageDialog(this, "Campo E-mail vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtEmail.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtEmail.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtRua.getText()) || val.isNull(this.txtRua.getText()))
        {
            JOptionPane.showMessageDialog(this, "Campo nome da rua está vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtRua.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtRua.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtBairro.getText()) || val.isNull(this.txtBairro.getText()))
        {
            JOptionPane.showMessageDialog(this, "Campo nome do bairro está vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtBairro.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtBairro.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtCidade.getText()) || val.isNull(this.txtCidade.getText()))
        {
            JOptionPane.showMessageDialog(this, "Campo nome da cidade está vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtCidade.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtCidade.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtComplemento.getText()) || val.isNull(this.txtComplemento.getText()))
        {
            JOptionPane.showMessageDialog(this, "Campo complemento vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtComplemento.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtComplemento.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.txtCep, "  .   -   ") || val.isNull(this.txtCep, null))
        {
            JOptionPane.showMessageDialog(this, "Campo número de cep está vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtCep.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtCep.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(val.isEmpty(this.spinerNumero.getValue().toString()) || val.isNull(this.spinerNumero.getValue().toString()))
        {
            JOptionPane.showMessageDialog(this, "Campo número da casa está vázio, porfavor preencher!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.spinerNumero.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.spinerNumero.setBorder(new LineBorder(Color.BLACK));
        }
        
        if(!val.isEmailValid(this.txtEmail.getText()))
        {
            JOptionPane.showMessageDialog(this, "O email digitado é inválido, porfavor digite corretamente!", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.txtEmail.setBorder(new LineBorder(Color.RED));
            return false;
        }
        else
        {
            this.txtEmail.setBorder(new LineBorder(Color.BLACK));
        }
        
        
        return true;
    }
    
    
    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        // TODO add your handling code here:
     
        this.btnCadastrar.setBorder(new LineBorder(Color.black));
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        // TODO add your handling code here:

        this.btnCadastrar.setBorder(null);
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        // TODO add your handling code here:
        this.btnCadastrar.setBorder(new LineBorder(Color.RED));
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseExited
        // TODO add your handling code here:
        this.btnLimpar.setBorder(null);
    }//GEN-LAST:event_btnLimparMouseExited

    private void btnLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseEntered
        // TODO add your handling code here:
        this.btnLimpar.setBorder(new LineBorder(Color.black));
    }//GEN-LAST:event_btnLimparMouseEntered

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        this.txtBairro.setText("");
        this.txtCelP.setText("");
        this.txtCelS.setText("");
        this.txtCep.setText("");
        this.txtCidade.setText("");
        this.txtComplemento.setText("");
        this.txtCpf.setText("");
        this.txtDtNasc.setText("");
        this.txtEmail.setText("");
        this.txtNome.setText("");
        this.txtRg.setText("");
        this.txtRua.setText("");
        this.spinerNumero.setValue(0);
        JOptionPane.showMessageDialog(this, "Campos limpos!");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        this.btnHome.setBorder(null);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        this.btnHome.setBorder(new LineBorder(Color.black));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        TelaPrincipal casa = new TelaPrincipal();
        casa.setVisible(true);
        this.setDefaultCloseOperation(TelaPrincipal.EXIT_ON_CLOSE);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> comboxEstado;
    private javax.swing.JComboBox<String> comboxEstadoCivil;
    private javax.swing.JComboBox<String> comboxSexo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JMenuItem menuItemBack;
    private javax.swing.JMenuItem menuItemHome;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JPanel panelEndereco;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JSpinner spinerNumero;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelP;
    private javax.swing.JFormattedTextField txtCelS;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDtNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
